# -*- coding: utf-8 -*-
"""Pro-107.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D3aRvabAJZtV7tzHg12jngEbBGfXCgrw
"""

import csv
import pandas as pd 
import plotly.express as px 

df = pd.read_csv("data2.csv")
mean = df.groupby(["student_id", "level"], as_index = False)["attempt"].mean()
fig = px.scatter(mean, x="student_id",
                 y="level",
                 size="attempt", 
                 color="attempt")

fig.show()